(09/04/2018 15:46:19) ******************************************************
(09/04/2018 15:46:19) Iniciando proceso de creacion de Workitem
(09/04/2018 15:46:19) Fecha/Hora (Inicio)	: 09/04/2018 15:46:19
(09/04/2018 15:46:19) Nro. Proceso		: 14970
(09/04/2018 15:46:19) Usuario			: fallas
(09/04/2018 15:46:19) Cliente			: 192.168.100.35
(09/04/2018 15:46:19) Cod. Remedy		: INC000001089654
(09/04/2018 15:46:19) Componente		: SISACT_2
(09/04/2018 15:46:19) Soap Tecnico		: C12101
(09/04/2018 15:46:19) ******************************************************
(09/04/2018 15:46:19)
(09/04/2018 15:46:19) Creando workitems . . .
(09/04/2018 15:46:19) 
(09/04/2018 15:46:42) Se creo con exito: 109575|INC000001089654
(09/04/2018 15:49:33) Ocurrio un error: Exception getting attribute representation: [Aplicacion] Value: [SISACT_2]  Original exception: 
Type could not be identified - Enumeration could not be resolved: Aplicacion Value: SISACT_2
Failed!|FALLA.INC000001089654.SISACT_2
